### ISSUE TITLE
Cannot import name Connection

### ISSUE THREAD

**Issue by Alex85651** [shinken-monitoring/mod-retention-mongodb#16] opened 2016-10-19 08:01 UTC
Hi guys,
I had an error while trying to make this module work
`Cannot import name Connection`

This was caused by this import 
`try:`
      `from pymongo.connection import Connection`
`except ImportError:`
      `Connection = None`

It appears that since the version 3.0 of pymongo, the module Connection does no longer exist and can now be found in the MongoClient package. So I decided to change the part of the code that no longer work.
`try:`
       `from pymongo import MongoClient as Connection`
`except ImportError:`
      `Connection = None`

It would be great to update this :)

**Comment by thabend0r** [comment] 2016-11-23 10:18
Hey,
I got the same error. seems this packages is very outdated.

when making the change suggested above i get the following error:

[1479896067] ERROR: [Shinken] The module retention-mongodb raised an exception 'Module' object has no attribute 'uri', I remove it! traceback=Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/shinken/modulesmanager.py", line 234, in get_instances
    inst = module.get_instance(mod_conf)
  File "/var/lib/shinken/modules/retention-mongodb/module.py", line 66, in get_instance
    uri = plugin.uri
AttributeError: 'Module' object has no attribute 'uri'

**Comment by clonedagain** [comment] 2017-03-08 09:25
Isn't this a duplicate of #8  ?

**Comment by olivierHa** [comment] 2017-03-08 09:39
I think so. Could you try with master version of this module if you got an issue ?

**Closed** 2017-03-08 09:43 UTC

**Comment by clonedagain** [comment] 2017-03-08 09:50
master works for me, following these steps:
- ``shinken install retention-mongodb``
- cloned this repo to /tmp
- copied /tmp/mod-retention-mongodb/module/* to /var/lib/shinken/modules/retention-mongodb/
- restarted shinken
